### ISSUE TITLE
pico w can't handle request

### ISSUE THREAD

**Issue by abuvanth** [kevinmcaleer/kevsrobots.com#15]
2022-12-28 14:01:45 [debug    / 124kB] Get request
Task exception wasn't retrieved
future: <Task> coro= <generator object '_handle_request' at 20011000>
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "/lib/phew/server.py", line 298, in _handle_request
  File "/lib/phew/template.py", line 7, in render_template
OSError: [Errno 2] ENOENT

**Comment by abuvanth** [comment]
issue resolved after copied index.html into pico
